<?php
require_once('cozyextentions/cozywebtest.php');

class SubmissionsWebTestCase extends CozyWebTestCase{
	
	public function testSubmitSubmission(){
		$this->selenium->open("/");
		$this->selenium->click("link=Login");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("UserUsername", "user");
		$this->selenium->type("UserPassword", "password");
		$this->selenium->click("//input[@value='Login']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("//img[@alt='submit topic']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Puzzles");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("//img[@alt='submit topic']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("TopicTitle", "test 1");
		$this->selenium->type("TopicText", "test 1");
		$this->selenium->click("DataStructureDataStructure7");
		$this->selenium->click("AlgorithmAlgorithm10");
		$this->selenium->type("TopicCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Submit your topic']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("//img[@alt='Submit my solution to the puzzle']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("SubmissionTitle", "solution 1");
		$this->selenium->type("SubmissionDescription1", "solution 1");
		$this->selenium->type("SubmissionText1", "solution 1");
		$this->selenium->select("SubmissionSyntax", "label=D");
		$this->selenium->type("SubmissionCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Submit']");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isElementPresent("link=solution 1"));
		$this->assertTrue($this->selenium->isTextPresent("1 point | by user | edit"));
		$this->assertTrue($this->selenium->isTextPresent("Size: 10"));
		$this->selenium->click("link=solution 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("1 point | by user | edit"));
		$this->assertTrue($this->selenium->isTextPresent("solution 1"));
		$this->assertTrue($this->selenium->isElementPresent("newcommentformtext"));
		$this->selenium->click("link=Puzzles");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Logout");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("1 point | by user"));
		$this->selenium->click("link=solution 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("1 point | by user"));
	}
	
	public function testEditSubmission(){
		$this->selenium->open("/");
		$this->selenium->click("link=Login");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("UserUsername", "user");
		$this->selenium->type("UserPassword", "password");
		$this->selenium->click("//input[@value='Login']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("//img[@alt='submit topic']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("TopicTitle", "test 1");
		$this->selenium->type("TopicText", "test 1");
		$this->selenium->click("DataStructureDataStructure1");
		$this->selenium->click("AlgorithmAlgorithm4");
		$this->selenium->type("TopicCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Submit your topic']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Logout");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Register");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("UserUsername", "testuser");
		$this->selenium->type("UserEmail", "testuser@test.com");
		$this->selenium->type("UserPasswordNew", "password");
		$this->selenium->type("UserPasswordConfirm", "password");
		$this->selenium->type("UserCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Register']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("//img[@alt='Submit my solution to the puzzle']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("SubmissionTitle", "solution 1");
		$this->selenium->type("SubmissionDescription1", "solution 1");
		$this->selenium->type("SubmissionText1", "solution 1");
		$this->selenium->type("SubmissionCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Submit']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=solution 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("solution 1"));
		$this->assertTrue($this->selenium->isTextPresent("1 point | by testuser | edit"));
		$this->selenium->click("link=edit");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("SubmissionTitle", "solution 1 edit title");
		$this->selenium->type("SubmissionDescription1", "solution 1 edit description");
		$this->selenium->type("SubmissionText1", "solution 1 edit code");
		$this->selenium->select("SubmissionSyntax", "label=Lua");
		$this->selenium->click("//input[@value='Submit']");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("solution 1 edit title"));
		try {
		$this->assertTrue($this->selenium->isTextPresent("1 point | by testuser | edit"));
		} catch (PHPUnit_Framework_AssertionFailedError $e) {
		array_push($this->verificationErrors, $e->toString());
		}
		$this->assertTrue($this->selenium->isTextPresent("solution 1 edit description"));
		$this->assertTrue($this->selenium->isTextPresent("solution 1 edit code"));
		$this->selenium->click("link=edit");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Logout");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Login");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("UserUsername", "user");
		$this->selenium->type("UserPassword", "password");
		$this->selenium->click("//input[@value='Login']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test 1");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("1 point | by testuser"));
		$this->selenium->click("link=solution 1 edit title");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=solution 1 edit title");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("solution 1 edit description"));
		$this->assertTrue($this->selenium->isTextPresent("solution 1 edit title"));
		$this->selenium->click("link=Logout");
	}
	
	public function testsubmissionVote(){
		$this->selenium->open("/");
		$this->selenium->click("link=Login");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("UserUsername", "user");
		$this->selenium->type("UserPassword", "password");
		$this->selenium->click("//input[@value='Login']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("//img[@alt='submit topic']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("TopicTitle", "test puzzle");
		$this->selenium->type("TopicTitle", "test puzzle title");
		$this->selenium->type("TopicText", "puzzle text");
		$this->selenium->click("DataStructureDataStructure1");
		$this->selenium->click("AlgorithmAlgorithm4");
		$this->selenium->type("TopicCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Submit your topic']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Logout");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Register");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("UserUsername", "testuser");
		$this->selenium->type("UserEmail", "testuser@test.com");
		$this->selenium->type("UserPasswordNew", "password");
		$this->selenium->type("UserPasswordConfirm", "password");
		$this->selenium->type("UserCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Register']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test puzzle title");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("//img[@alt='Submit my solution to the puzzle']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("SubmissionTitle", "this is my test solution title");
		$this->selenium->type("SubmissionDescription1", "my test solution text");
		$this->selenium->type("SubmissionText1", "my text");
		$this->selenium->select("SubmissionSyntax", "label=Ruby");
		$this->selenium->type("SubmissionCaptcha", "automatedtest");
		$this->selenium->click("//input[@value='Submit']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("downvoteimg1");
		$this->assertTrue($this->selenium->isTextPresent("0 points | by testuser | edit"));
		$this->selenium->click("logo");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test puzzle title");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("-1 point | by testuser | edit"));
		$this->selenium->click("upvoteimg1");
		$this->assertTrue($this->selenium->isTextPresent("0 points | by testuser | edit"));
		$this->selenium->click("logo");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test puzzle title");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("1 point | by testuser | edit"));
		$this->selenium->click("upvoteimg1");
		$this->selenium->click("upvoteimg1");
		$this->selenium->click("upvoteimg1");
		$this->assertTrue($this->selenium->isTextPresent("1 point | by testuser | edit"));
		$this->selenium->click("downvoteimg1");
		$this->selenium->click("logo");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test puzzle title");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("downvoteimg1");
		$this->selenium->click("downvoteimg1");
		$this->selenium->click("downvoteimg1");
		try {
		$this->assertTrue($this->selenium->isTextPresent("-1 point | by testuser | edit"));
		} catch (PHPUnit_Framework_AssertionFailedError $e) {
		array_push($this->verificationErrors, $e->toString());
		}
		$this->selenium->click("link=Logout");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=Login");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->type("UserUsername", "user");
		$this->selenium->type("UserPassword", "password");
		$this->selenium->click("//input[@value='Login']");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test puzzle title");
		$this->selenium->waitForPageToLoad("50000");
		$this->assertTrue($this->selenium->isTextPresent("-1 point | by testuser"));
		$this->selenium->click("upvoteimg1");
		$this->assertTrue($this->selenium->isTextPresent("0 points | by testuser"));
		$this->selenium->click("logo");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test puzzle title");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("upvoteimg1");
		$this->selenium->click("upvoteimg1");
		$this->assertTrue($this->selenium->isTextPresent("0 points | by testuser"));
		$this->selenium->click("downvoteimg1");
		$this->selenium->click("logo");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("link=test puzzle title");
		$this->selenium->waitForPageToLoad("50000");
		$this->selenium->click("downvoteimg1");
		$this->selenium->click("downvoteimg1");
		$this->assertTrue($this->selenium->isTextPresent("-2 points | by testuser"));
		$this->selenium->click("link=Logout");
	}
}
?>